name: coran_warch
description: Application mobile du Coran Warsh

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dépendances utiles
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_svg: ^2.0.9
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: assets/images/icons/coran_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  # Activer si tu continues à utiliser les images locales :
  # Pour réduire la taille de l'app, il est recommandé de désactiver ces lignes
  # si tu utilises des images via lien GitHub.
  #
  # assets:
  #   - assets/files/
  #   - assets/images/icons/
  #   - assets/images/sourats/
